name: skin_monitor_pro
description: On-device skin monitoring app (Flutter + TFLite)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  image_picker: ^1.0.7
  google_fonts: ^6.2.1
  animations: ^2.0.11
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/labels.txt
    - assets/models/skin_classifier_quant.tflite
